apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
  name: webserver-{{ .Release.Name }}
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Chart.Name }}
  type: {{ .Values.service.type }}
status:
